import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Geoguessr AWS",
  description: "Generated by create next app",
};

export default function RootLayout({ children, hideNavbar = false }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {!hideNavbar && <Navbar></Navbar>}
        {children}
      </body>
    </html>
  );
}
